name: Deploy

on:
  push:
    branches: [ front ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: git config --global credential.helper 'cache --timeout=3600'
      - run: npm i
      
      - run: npm run build
      
      
      - run: ls .
      - run: cat .gitignore
      - run: find . -maxdepth 1 ! -name build ! -name . -exec rm -rf {} \;
      - run: git init
      - run: git remote add origin https://github.com/iamquoz/matstat.git
      - run: git fetch
      - run: git add . 
      - run: ls .
      
      - run: git config user.name "workflow"
      - run: git config user.email "lol@iamquoz.me"
      
      - run: git commit -m "[skip ci] build by workflows"
      - run: git push --set-upstream origin master
      - run: ls .
      
    
