name: Deploy

on:
  push:
    branches: [ front ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: npm i
      
      - run: npm run build
      
      
      - run: ls .
      - run: cat .gitignore
      - run: find . -maxdepth 1 ! -name build ! -name . -exec rm -rv {} \;
      - run: git init
      - run: git remote add origin https://github.com/iamquoz/matstat.git
      - run: git reset origin/master
      - run: git fetch
      - run: git checkout -t origin/master
      - run: git add . 
      
      - run: git config user.name "workflow"
      - run: git config user.email "lol@iamquoz.me"
      
      - run: git commmit -m "[skip ci] build by workflows"
      - run: git push
      - run: ls .
      
      
      # '[skip ci]' in the message doesn't cause a infinite loop 
      # since this is triggered upon push 
      
      # https://stackoverflow.com/a/66156840
      #- run: git commit -m "[skip ci] build by workflows"
      #- run: git push
