name: Deploy

on:
  push:
    branches: [ gena ]
  pull_request:
    branches: [ gena ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      
      # ??? but ok
      - run: git config user.name "workflow"
      - run: git config user.email "lol@iamquoz.me"
      - run: npm run build
      # im braindead and forgot to commit first yeah.
      - run: git add .
      # '[skip ci]' in the message doesn't turn cause a infinite loop 
      # https://stackoverflow.com/a/66156840
      - run: git commit -m "[skip ci] build by workflows"
      - run: git push
