name: Deploy

on:
  push:
    branches: [ gena ]
  pull_request:
    branches: [ gena ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: cat .gitignore
      - run: npm run build
      - run: ls -a
      - run: ls ./.. -a
      - run: ls ./build/ -a
      # this better work
      - run: git push
