name: Deploy

on:
  push:
    branches: [ front ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      
      - run: git config user.name "workflow"
      - run: git config user.email "lol@iamquoz.me"
      
      - run: npm i
      
      - run: npm run build
      
      - run: git checkout prod
      
      - run: git add .
      - run: git commit -m "[skip ci] build by workflows"
      
          
      
    
