name: Deploy

on:
  push:
    branches: [ front ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - run: npm i
      
      - run: npm run build
      
      - run: find . -maxdepth 1 ! -name build ! -name . -exec rm -rf {} \;
      - run: git init
      - run: git remote add origin https://github.com/iamquoz/matstat.git
      
      - run: git config user.name "workflow"
      - run: git config user.email "lol@iamquoz.me"
      
      - run: git add .
      - run: git commit -m "init"
      
      - run: git stash
      
      - run: git pull origin prod
      - run: git stash pop
      
      - run: git commit -m "[skip ci] build by workflows"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          
      
    
